import { Typography, Box, Card, CardContent, Grid, Button } from '@mui/material';
import { Download as DownloadIcon, PictureAsPdf as PdfIcon } from '@mui/icons-material';
import { ResponsiveContainer, PieChart, Pie, Tooltip, Legend } from 'recharts';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const data = [
  { name: 'Widget A', value: 400, fill: '#3b82f6' },
  { name: 'Gadget B', value: 300, fill: '#10b981' },
  { name: 'Component C', value: 300, fill: '#f59e0b' },
  { name: 'Assembly D', value: 200, fill: '#8b5cf6' },
];

export default function ReportsAnalytics() {
  const handleGeneratePDF = () => {
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.text('Quarterly Production Report', 14, 22);
    
    // Add Subtitle
    doc.setFontSize(12);
    doc.text('TsukiFlow Manufacturing ERP - Q3 2026', 14, 30);
    
    // Add a table of data
    doc.autoTable({
      startY: 40,
      head: [['Product/Component', 'Units Produced', 'Status']],
      body: [
        ['Widget A', '400', 'Completed'],
        ['Gadget B', '300', 'In Progress'],
        ['Component C', '300', 'Completed'],
        ['Assembly D', '200', 'Planned'],
        ['Custom Gear X', '150', 'Failed QC'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] },
    });

    // Add footer text
    doc.setFontSize(10);
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.text(
        `Generated by YUZU | TsukiFlow | Page ${i} of ${pageCount}`,
        14,
        doc.internal.pageSize.height - 10
      );
    }

    // Save the PDF
    doc.save('TsukiFlow_Q3_Report.pdf');
  };

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 5, alignItems: 'center', flexWrap: 'wrap', gap: 2 }}>
        <Box>
          <Typography variant="h4" fontWeight="bold" gutterBottom>Reports & Analytics</Typography>
          <Typography variant="body1" color="text.secondary">Export detailed analytics and review historical data.</Typography>
        </Box>
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button variant="outlined" color="primary" startIcon={<DownloadIcon />}>Export CSV</Button>
          <Button variant="contained" color="secondary" startIcon={<PdfIcon />} onClick={handleGeneratePDF}>Generate PDF</Button>
        </Box>
      </Box>

      <Grid container spacing={3}>
        <Grid item xs={12} md={6}>
          <Card className="hover-lift" sx={{ height: 400, display: 'flex', flexDirection: 'column' }}>
            <CardContent sx={{ flexGrow: 1, display: 'flex', flexDirection: 'column' }}>
              <Typography variant="h6" fontWeight="bold" mb={2}>Production Distribution</Typography>
              <Box sx={{ flexGrow: 1, minHeight: 0 }}>
                <ResponsiveContainer width="100%" height="100%">
                  <PieChart>
                    <Pie data={data} cx="50%" cy="50%" innerRadius={80} outerRadius={120} paddingAngle={5} dataKey="value" stroke="none" />
                    <Tooltip contentStyle={{ backgroundColor: '#1e293b', border: 'none', borderRadius: 8, color: '#f8fafc' }} />
                    <Legend height={36}/>
                  </PieChart>
                </ResponsiveContainer>
              </Box>
            </CardContent>
          </Card>
        </Grid>
        <Grid item xs={12} md={6}>
          <Grid container spacing={3}>
            <Grid item xs={12}>
               <Card className="hover-lift" sx={{ bgcolor: 'rgba(59, 130, 246, 0.1)', border: '1px solid rgba(59, 130, 246, 0.3)' }}>
                <CardContent sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Box>
                    <Typography variant="h5" fontWeight="bold" color="primary.main">Quarterly Production Report</Typography>
                    <Typography variant="body2" color="text.secondary">Auto-generated summary for Q3 2026</Typography>
                  </Box>
                  <Button variant="contained">View</Button>
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12}>
               <Card className="hover-lift" sx={{ bgcolor: 'rgba(16, 185, 129, 0.1)', border: '1px solid rgba(16, 185, 129, 0.3)' }}>
                <CardContent sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Box>
                    <Typography variant="h5" fontWeight="bold" color="success.main">Yield Optimization Analysis</Typography>
                    <Typography variant="body2" color="text.secondary">AI generated insight report</Typography>
                  </Box>
                  <Button variant="contained" color="success">View</Button>
                </CardContent>
              </Card>
            </Grid>
            <Grid item xs={12}>
               <Card className="hover-lift" sx={{ bgcolor: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.3)' }}>
                <CardContent sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Box>
                    <Typography variant="h5" fontWeight="bold" color="warning.main">Supply Chain Forecast</Typography>
                    <Typography variant="body2" color="text.secondary">Predictive modeling for next 30 days</Typography>
                  </Box>
                  <Button variant="contained" color="warning">View</Button>
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </Box>
  );
}
